// Copyright (C) 2011-2012.
// Author: Marcello Esposito (esposito.marce@gmail.com)
//
// This file is part of SMSRobot.
//   
// SMSRobot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//   
// SMSRobot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//   
// You should have received a copy of the GNU General Public License
// along with SMSRobot; see the file COPYING. If not, see
// <http://www.gnu.org/licenses/> and write to esposito.marce@gmail.com.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsPush.SMSEnqueuer {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsState", Namespace="http://schemas.datacontract.org/2004/07/SMSSender.Entities")]
    public enum SmsState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enqueued = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSEnqueuer.ISMSEnqueuerWcf")]
    public interface ISMSEnqueuerWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSEnqueuerWcf/SendSMS", ReplyAction="http://tempuri.org/ISMSEnqueuerWcf/SendSMSResponse")]
        void SendSMS(string phoneNumber, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSEnqueuerWcf/SendSMS2", ReplyAction="http://tempuri.org/ISMSEnqueuerWcf/SendSMS2Response")]
        string SendSMS2(string phoneNumber, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSEnqueuerWcf/GetSmsStateById", ReplyAction="http://tempuri.org/ISMSEnqueuerWcf/GetSmsStateByIdResponse")]
        SmsPush.SMSEnqueuer.SmsState GetSmsStateById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSEnqueuerWcf/GetSmsStateByIds", ReplyAction="http://tempuri.org/ISMSEnqueuerWcf/GetSmsStateByIdsResponse")]
        System.Collections.Generic.Dictionary<string, SmsPush.SMSEnqueuer.SmsState> GetSmsStateByIds(string[] ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISMSEnqueuerWcfChannel : SmsPush.SMSEnqueuer.ISMSEnqueuerWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SMSEnqueuerWcfClient : System.ServiceModel.ClientBase<SmsPush.SMSEnqueuer.ISMSEnqueuerWcf>, SmsPush.SMSEnqueuer.ISMSEnqueuerWcf {
        
        public SMSEnqueuerWcfClient() {
        }
        
        public SMSEnqueuerWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSEnqueuerWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSEnqueuerWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSEnqueuerWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendSMS(string phoneNumber, string message) {
            base.Channel.SendSMS(phoneNumber, message);
        }
        
        public string SendSMS2(string phoneNumber, string message) {
            return base.Channel.SendSMS2(phoneNumber, message);
        }
        
        public SmsPush.SMSEnqueuer.SmsState GetSmsStateById(string id) {
            return base.Channel.GetSmsStateById(id);
        }
        
        public System.Collections.Generic.Dictionary<string, SmsPush.SMSEnqueuer.SmsState> GetSmsStateByIds(string[] ids) {
            return base.Channel.GetSmsStateByIds(ids);
        }
    }
}
